### ISSUE TITLE
Remove "Blog" from tab title

### ISSUE THREAD

**Issue by etam22** [howinator/GimmeThat#3]
Remove "Blog" from tab title "Gimme That Blog".

**Comment by howinator** [comment]
When the actual blog entry opens, do you want the tab to say the name of the blog post or do you want it to stay "Gimme That". What I mean is: do you want the blog entry titled "Milo's Bone Recipe" to say "Milo's Bone Recipe" in the tab or "Gimme That"?

**Comment by howinator** [comment]
Right not it is "Gimme That Blog | Milo's Bone Recipe"

**Comment by etam22** [comment]
"Gimme That Blog | Milo's Bone Recipe" is fine

**Comment by etam22** [comment]
CORRECTION: "Gimme That | Milo's Bone Recipe"

**Comment by howinator** [comment]
Fixed. Closing now
